# Generated by Django 4.2.6 on 2023-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
