# Generated by Django 4.2.6 on 2023-10-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0006_post_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='animations/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
