# Generated by Django 4.2.6 on 2023-10-17 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0009_post_post_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='author',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning_app.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning_app.question')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.choice'),
        ),
        migrations.AddField(
            model_name='result',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_app.question'),
        ),
    ]
