# Generated by Django 4.2.6 on 2023-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0012_remove_submission_exercise_remove_submission_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple choice')], default='MC', max_length=4),
        ),
    ]
