# Generated by Django 4.2.6 on 2023-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0013_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
