# Generated by Django 4.2.6 on 2023-11-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0018_remove_subject_code_remove_subject_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning_app.exercise'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning_app.lesson'),
        ),
    ]
