# Generated by Django 4.2.6 on 2023-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0019_course_exercises_course_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
