# Generated by Django 4.2.6 on 2023-11-06 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_app', '0021_rename_teacher_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
