# Generated by Django 4.2.6 on 2023-11-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0025_alter_useranswer_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.attempt'),
        ),
    ]
