# Generated by Django 4.2.6 on 2023-11-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0028_remove_question_subject_alter_attempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning_app.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning_app.course'),
        ),
    ]
