# Generated by Django 4.2.6 on 2023-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0032_weightedscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning_app.exercisecategory'),
        ),
    ]
