# Generated by Django 4.2.6 on 2023-11-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0033_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
