# Generated by Django 4.2.6 on 2023-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0036_remove_course_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
    ]
