# Generated by Django 4.2.7 on 2023-11-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0038_remove_course_categories_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='learning_app.exercisecategory'),
        ),
    ]
